version: "3.1"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./replica.key:/replica.key
    entrypoint:
      - bash
      - -c
      - |
        cp /replica.key /data/replica.key
        chmod 400 /data/replica.key
        chown 999:999 /data/replica.key
        exec docker-entrypoint.sh $$@
    command:
      ["--bind_ip_all", "--replSet", "rs", "--keyFile", "/data/replica.key"]

  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://root:password@host.docker.internal:27017/?authSource=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
